CREATE DATABASE IF NOT EXISTS CANCER_ONCOLOGY_DB;
USE DATABASE CANCER_ONCOLOGY_DB;
SELECT CURRENT_DATABASE();
CREATE SCHEMA IF NOT EXISTS CANCER_ONCOLOGY_DB.ONCOLOGY_RAW;

CREATE SCHEMA IF NOT EXISTS CANCER_ONCOLOGY_DB.ONCOLOGY_DW;

CREATE SCHEMA IF NOT EXISTS CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC;

CREATE SCHEMA IF NOT EXISTS CANCER_ONCOLOGY_DB.ONCOLOGY_OPS;

CREATE SCHEMA IF NOT EXISTS CANCER_ONCOLOGY_DB.ONCOLOGY_STREAMLIT;
SHOW SCHEMAS IN DATABASE CANCER_ONCOLOGY_DB;
CREATE WAREHOUSE IF NOT EXISTS CANCER_ONCOLOGY_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;
USE WAREHOUSE CANCER_ONCOLOGY_WH;
CREATE OR REPLACE FILE FORMAT CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
FILE_FORMAT = CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_CSV_FORMAT;

LIST @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE;

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS
(
    PATIENT_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    DOB DATE,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    SEGMENT VARCHAR,
    PAYER_ID VARCHAR,
    UPDATED_AT TIMESTAMP,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME VARCHAR
);

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PROVIDERS
(
    PROVIDER_ID VARCHAR,
    PROVIDER_NAME VARCHAR,
    PROVIDER_TYPE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR,
    ACCREDITATION VARCHAR,
    STATUS VARCHAR,
    OPEN_DATE DATE,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME VARCHAR
);

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG
(
    CANCER_CODE VARCHAR,
    CANCER_NAME VARCHAR,
    CANCER_GROUP VARCHAR,
    ICD10_CODE VARCHAR,
    SPECIALTY VARCHAR,
    STATUS VARCHAR,
    UPDATED_AT TIMESTAMP,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME VARCHAR
);

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS
(
    ENCOUNTER_ID VARCHAR,
    ENCOUNTER_LINE_ID NUMBER,
    SERVICE_DATE DATE,
    PATIENT_ID VARCHAR,
    PROVIDER_ID VARCHAR,
    CANCER_CODE VARCHAR,
    DISEASE_STAGE VARCHAR,
    TREATMENT_TYPE VARCHAR,
    REGIMEN_CODE VARCHAR,
    BILLED_AMOUNT NUMBER(18,2),
    PAYMENT_MODE VARCHAR,
    ENCOUNTER_STATUS VARCHAR,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME VARCHAR
);

SHOW TABLES IN SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_RAW;

LIST @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE;

COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS
(
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    CITY,
    STATE,
    COUNTRY,
    SEGMENT,
    PAYER_ID,
    UPDATED_AT,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILES = ('oncology_patients.csv')
ON_ERROR = 'CONTINUE';

COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PROVIDERS
(
    PROVIDER_ID,
    PROVIDER_NAME,
    PROVIDER_TYPE,
    CITY,
    STATE,
    REGION,
    ACCREDITATION,
    STATUS,
    OPEN_DATE,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILES = ('oncology_providers.csv')
ON_ERROR = 'CONTINUE';

COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG
(
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,
    UPDATED_AT,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILES = ('cancer_catalog.csv')
ON_ERROR = 'CONTINUE';

COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS
(
    ENCOUNTER_ID,
    ENCOUNTER_LINE_ID,
    SERVICE_DATE,
    PATIENT_ID,
    PROVIDER_ID,
    CANCER_CODE,
    DISEASE_STAGE,
    TREATMENT_TYPE,
    REGIMEN_CODE,
    BILLED_AMOUNT,
    PAYMENT_MODE,
    ENCOUNTER_STATUS,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILES = ('oncology_encounters.csv')
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) AS PATIENT_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS;

SELECT COUNT(*) AS PROVIDER_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PROVIDERS;

SELECT COUNT(*) AS CANCER_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG;

SELECT COUNT(*) AS ENCOUNTER_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS
LIMIT 10;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PROVIDERS
LIMIT 10;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG
LIMIT 10;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS
LIMIT 10;

SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS',
        START_TIME => DATEADD('hour', -1, CURRENT_TIMESTAMP())
    )
);

USE DATABASE CANCER_ONCOLOGY_DB;

USE SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_DW;

USE WAREHOUSE CANCER_ONCOLOGY_WH;

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_DATE
(
    DATE_SK NUMBER PRIMARY KEY,
    FULL_DATE DATE,
    DAY NUMBER,
    MONTH NUMBER,
    MONTH_NAME VARCHAR,
    QUARTER NUMBER,
    YEAR NUMBER,
    DAY_OF_WEEK NUMBER,
    DAY_NAME VARCHAR
);

INSERT INTO CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_DATE
(
    DATE_SK,
    FULL_DATE,
    DAY,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR,
    DAY_OF_WEEK,
    DAY_NAME
)
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_SK,
    DATE_VALUE,
    DAY(DATE_VALUE),
    MONTH(DATE_VALUE),
    MONTHNAME(DATE_VALUE),
    QUARTER(DATE_VALUE),
    YEAR(DATE_VALUE),
    DAYOFWEEK(DATE_VALUE),
    DAYNAME(DATE_VALUE)
FROM
(
    SELECT DATEADD(
        DAY,
        SEQ4(),
        (SELECT MIN(SERVICE_DATE)
         FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS)
    )::DATE AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 1000))
)
WHERE DATE_VALUE <=
(
    SELECT MAX(SERVICE_DATE)
    FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS
);

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_DATE
ORDER BY FULL_DATE;

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PROVIDER
(
    PROVIDER_SK NUMBER AUTOINCREMENT,
    PROVIDER_ID VARCHAR,
    PROVIDER_NAME VARCHAR,
    PROVIDER_TYPE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR,
    ACCREDITATION VARCHAR,
    STATUS VARCHAR,
    OPEN_DATE DATE,
    PRIMARY KEY (PROVIDER_SK)
);

INSERT INTO CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PROVIDER
(
    PROVIDER_ID,
    PROVIDER_NAME,
    PROVIDER_TYPE,
    CITY,
    STATE,
    REGION,
    ACCREDITATION,
    STATUS,
    OPEN_DATE
)
SELECT
    PROVIDER_ID,
    PROVIDER_NAME,
    PROVIDER_TYPE,
    CITY,
    STATE,
    REGION,
    ACCREDITATION,
    STATUS,
    OPEN_DATE
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PROVIDERS;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PROVIDER;

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
(
    PATIENT_SK NUMBER AUTOINCREMENT,
    PATIENT_ID VARCHAR,

    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    DOB DATE,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    SEGMENT VARCHAR,
    PAYER_ID VARCHAR,

    HASH_DIFF VARCHAR,

    EFF_START_TS TIMESTAMP,
    EFF_END_TS TIMESTAMP,

    IS_CURRENT BOOLEAN,

    LOAD_TS TIMESTAMP
);

INSERT INTO CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
(
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    CITY,
    STATE,
    COUNTRY,
    SEGMENT,
    PAYER_ID,
    HASH_DIFF,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    LOAD_TS
)
SELECT
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    CITY,
    STATE,
    COUNTRY,
    SEGMENT,
    PAYER_ID,

    MD5(
        CONCAT_WS('|',
            COALESCE(GENDER, ''),
            COALESCE(CITY, ''),
            COALESCE(STATE, ''),
            COALESCE(COUNTRY, ''),
            COALESCE(SEGMENT, ''),
            COALESCE(PAYER_ID, '')
        )
    ) AS HASH_DIFF,

    COALESCE(UPDATED_AT, CURRENT_TIMESTAMP()) AS EFF_START_TS,

    '9999-12-31 23:59:59'::TIMESTAMP AS EFF_END_TS,

    TRUE AS IS_CURRENT,

    CURRENT_TIMESTAMP() AS LOAD_TS

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
ORDER BY PATIENT_ID;

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
(
    CANCER_SK NUMBER AUTOINCREMENT,

    CANCER_CODE VARCHAR,
    CANCER_NAME VARCHAR,
    CANCER_GROUP VARCHAR,
    ICD10_CODE VARCHAR,
    SPECIALTY VARCHAR,
    STATUS VARCHAR,

    HASH_DIFF VARCHAR,

    EFF_START_TS TIMESTAMP,
    EFF_END_TS TIMESTAMP,

    IS_CURRENT BOOLEAN,

    LOAD_TS TIMESTAMP
);

INSERT INTO CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
(
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,
    HASH_DIFF,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    LOAD_TS
)
SELECT
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,

    MD5(
        CONCAT_WS('|',
            COALESCE(CANCER_NAME, ''),
            COALESCE(CANCER_GROUP, ''),
            COALESCE(ICD10_CODE, ''),
            COALESCE(SPECIALTY, ''),
            COALESCE(STATUS, '')
        )
    ) AS HASH_DIFF,

    COALESCE(UPDATED_AT, CURRENT_TIMESTAMP()) AS EFF_START_TS,

    '9999-12-31 23:59:59'::TIMESTAMP AS EFF_END_TS,

    TRUE AS IS_CURRENT,

    CURRENT_TIMESTAMP() AS LOAD_TS

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
ORDER BY CANCER_CODE;

CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER
(
    ENCOUNTER_SK NUMBER AUTOINCREMENT,

    ENCOUNTER_ID VARCHAR,
    ENCOUNTER_LINE_ID NUMBER,

    DATE_SK NUMBER,
    PATIENT_SK NUMBER,
    PROVIDER_SK NUMBER,
    CANCER_SK NUMBER,

    PATIENT_ID VARCHAR,
    PROVIDER_ID VARCHAR,
    CANCER_CODE VARCHAR,

    DISEASE_STAGE VARCHAR,
    TREATMENT_TYPE VARCHAR,
    REGIMEN_CODE VARCHAR,

    BILLED_AMOUNT NUMBER(18,2),
    PAYMENT_MODE VARCHAR,
    ENCOUNTER_STATUS VARCHAR,

    LOAD_TS TIMESTAMP
);

INSERT INTO CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER
(
    ENCOUNTER_ID,
    ENCOUNTER_LINE_ID,

    DATE_SK,
    PATIENT_SK,
    PROVIDER_SK,
    CANCER_SK,

    PATIENT_ID,
    PROVIDER_ID,
    CANCER_CODE,

    DISEASE_STAGE,
    TREATMENT_TYPE,
    REGIMEN_CODE,

    BILLED_AMOUNT,
    PAYMENT_MODE,
    ENCOUNTER_STATUS,

    LOAD_TS
)
SELECT
    E.ENCOUNTER_ID,
    E.ENCOUNTER_LINE_ID,

    D.DATE_SK,
    P.PATIENT_SK,
    PR.PROVIDER_SK,
    C.CANCER_SK,

    E.PATIENT_ID,
    E.PROVIDER_ID,
    E.CANCER_CODE,

    E.DISEASE_STAGE,
    E.TREATMENT_TYPE,
    E.REGIMEN_CODE,

    E.BILLED_AMOUNT,
    E.PAYMENT_MODE,
    E.ENCOUNTER_STATUS,

    CURRENT_TIMESTAMP()

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS E

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_DATE D
    ON E.SERVICE_DATE = D.FULL_DATE

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PROVIDER PR
    ON E.PROVIDER_ID = PR.PROVIDER_ID

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT P
    ON E.PATIENT_ID = P.PATIENT_ID
    AND P.IS_CURRENT = TRUE

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER C
    ON E.CANCER_CODE = C.CANCER_CODE
    AND C.IS_CURRENT = TRUE;

SELECT COUNT(*)
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER
ORDER BY ENCOUNTER_ID, ENCOUNTER_LINE_ID;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER
WHERE DATE_SK IS NULL
   OR PATIENT_SK IS NULL
   OR PROVIDER_SK IS NULL
   OR CANCER_SK IS NULL;
--snowpipe
CREATE OR REPLACE PIPE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.PIPE_PATIENTS
AUTO_INGEST = FALSE
AS
COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS
(
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    CITY,
    STATE,
    COUNTRY,
    SEGMENT,
    PAYER_ID,
    UPDATED_AT,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILE_FORMAT = (
    FORMAT_NAME = CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_CSV_FORMAT
)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.PIPE_PROVIDERS
AUTO_INGEST = FALSE
AS
COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PROVIDERS
(
    PROVIDER_ID,
    PROVIDER_NAME,
    PROVIDER_TYPE,
    CITY,
    STATE,
    REGION,
    ACCREDITATION,
    STATUS,
    OPEN_DATE,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILE_FORMAT = (
    FORMAT_NAME = CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_CSV_FORMAT
)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.PIPE_CANCER_CATALOG
AUTO_INGEST = FALSE
AS
COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG
(
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,
    UPDATED_AT,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILE_FORMAT = (
    FORMAT_NAME = CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_CSV_FORMAT
)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.PIPE_ENCOUNTERS
AUTO_INGEST = FALSE
AS
COPY INTO CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_ENCOUNTERS
(
    ENCOUNTER_ID,
    ENCOUNTER_LINE_ID,
    SERVICE_DATE,
    PATIENT_ID,
    PROVIDER_ID,
    CANCER_CODE,
    DISEASE_STAGE,
    TREATMENT_TYPE,
    REGIMEN_CODE,
    BILLED_AMOUNT,
    PAYMENT_MODE,
    ENCOUNTER_STATUS,
    SOURCE_FILE_NAME
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        METADATA$FILENAME
    FROM @CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_STAGE
)
FILE_FORMAT = (
    FORMAT_NAME = CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.ONCOLOGY_CSV_FORMAT
)
ON_ERROR = 'CONTINUE';
SHOW PIPES IN SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_RAW;
USE SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_OPS;
CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_OPS.LOAD_AUDIT
(
    AUDIT_ID NUMBER AUTOINCREMENT,
    BATCH_ID VARCHAR,
    PIPE_NAME VARCHAR,
    TABLE_NAME VARCHAR,
    SOURCE_FILE_NAME VARCHAR,
    LOAD_START_TS TIMESTAMP,
    LOAD_END_TS TIMESTAMP,
    SOURCE_ROW_COUNT NUMBER,
    LOADED_ROW_COUNT NUMBER,
    REJECTED_ROW_COUNT NUMBER,
    STATUS VARCHAR,
    ERROR_MESSAGE VARCHAR
);
CREATE OR REPLACE TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_OPS.REJECTS
(
    REJECT_ID NUMBER AUTOINCREMENT,
    BATCH_ID VARCHAR,
    SOURCE_FILE_NAME VARCHAR,
    SOURCE_ENTITY VARCHAR,
    REASON_CODE VARCHAR,
    REASON_DESCRIPTION VARCHAR,
    REJECTED_DATA VARCHAR,
    REJECT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
SHOW TABLES IN SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_OPS;
SELECT
    PATIENT_SK,
    PATIENT_ID,
    CITY,
    STATE,
    SEGMENT,
    PAYER_ID,
    HASH_DIFF,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
ORDER BY PATIENT_ID;

CREATE OR REPLACE TEMPORARY TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_PATIENT_SCD2
AS
SELECT
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    CITY,
    STATE,
    COUNTRY,
    SEGMENT,
    PAYER_ID,
    COALESCE(UPDATED_AT, CURRENT_TIMESTAMP()) AS UPDATED_AT,

    MD5(
        CONCAT_WS('|',
            COALESCE(GENDER, ''),
            COALESCE(CITY, ''),
            COALESCE(STATE, ''),
            COALESCE(COUNTRY, ''),
            COALESCE(SEGMENT, ''),
            COALESCE(PAYER_ID, '')
        )
    ) AS HASH_DIFF

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS;
SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_PATIENT_SCD2;
SELECT
    S.PATIENT_ID,
    S.HASH_DIFF AS NEW_HASH,
    D.HASH_DIFF AS OLD_HASH
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_PATIENT_SCD2 S
JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT D
    ON S.PATIENT_ID = D.PATIENT_ID
   AND D.IS_CURRENT = TRUE
WHERE S.HASH_DIFF <> D.HASH_DIFF;
SELECT
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    SEGMENT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS
LIMIT 5;

UPDATE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS
SET SEGMENT = 'REGULAR',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE PATIENT_ID = 'P0001';

CREATE OR REPLACE TEMPORARY TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_PATIENT_SCD2
AS
SELECT
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    CITY,
    STATE,
    COUNTRY,
    SEGMENT,
    PAYER_ID,
    COALESCE(UPDATED_AT, CURRENT_TIMESTAMP()) AS UPDATED_AT,

    MD5(
        CONCAT_WS('|',
            COALESCE(GENDER, ''),
            COALESCE(CITY, ''),
            COALESCE(STATE, ''),
            COALESCE(COUNTRY, ''),
            COALESCE(SEGMENT, ''),
            COALESCE(PAYER_ID, '')
        )
    ) AS HASH_DIFF

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_PATIENTS;
SELECT
    S.PATIENT_ID,
    S.SEGMENT AS NEW_SEGMENT,
    D.SEGMENT AS OLD_SEGMENT,
    S.HASH_DIFF AS NEW_HASH,
    D.HASH_DIFF AS OLD_HASH
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_PATIENT_SCD2 S
JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT D
    ON S.PATIENT_ID = D.PATIENT_ID
   AND D.IS_CURRENT = TRUE
WHERE S.HASH_DIFF <> D.HASH_DIFF;

UPDATE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT D
SET
    EFF_END_TS = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_PATIENT_SCD2 S
WHERE D.PATIENT_ID = S.PATIENT_ID
  AND D.IS_CURRENT = TRUE
  AND D.HASH_DIFF <> S.HASH_DIFF;

INSERT INTO CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
(
    PATIENT_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    CITY,
    STATE,
    COUNTRY,
    SEGMENT,
    PAYER_ID,
    HASH_DIFF,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    LOAD_TS
)
SELECT
    S.PATIENT_ID,
    S.FIRST_NAME,
    S.LAST_NAME,
    S.GENDER,
    S.DOB,
    S.CITY,
    S.STATE,
    S.COUNTRY,
    S.SEGMENT,
    S.PAYER_ID,
    S.HASH_DIFF,
    CURRENT_TIMESTAMP(),
    '9999-12-31 23:59:59'::TIMESTAMP,
    TRUE,
    CURRENT_TIMESTAMP()
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_PATIENT_SCD2 S
LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT D
    ON S.PATIENT_ID = D.PATIENT_ID
   AND D.IS_CURRENT = TRUE
WHERE D.PATIENT_ID IS NULL;

SELECT
    PATIENT_SK,
    PATIENT_ID,
    SEGMENT,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
WHERE PATIENT_ID = 'P0001'
ORDER BY EFF_START_TS;

SELECT
    CANCER_SK,
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,
    HASH_DIFF,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
ORDER BY CANCER_CODE;

CREATE OR REPLACE TEMPORARY TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_CANCER_SCD2
AS
SELECT
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,
    COALESCE(UPDATED_AT, CURRENT_TIMESTAMP()) AS UPDATED_AT,

    MD5(
        CONCAT_WS('|',
            COALESCE(CANCER_NAME, ''),
            COALESCE(CANCER_GROUP, ''),
            COALESCE(ICD10_CODE, ''),
            COALESCE(SPECIALTY, ''),
            COALESCE(STATUS, '')
        )
    ) AS HASH_DIFF

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG;

SELECT
    S.CANCER_CODE,
    S.CANCER_NAME,
    S.HASH_DIFF AS NEW_HASH,
    D.HASH_DIFF AS OLD_HASH
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_CANCER_SCD2 S
JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER D
    ON S.CANCER_CODE = D.CANCER_CODE
   AND D.IS_CURRENT = TRUE
WHERE S.HASH_DIFF <> D.HASH_DIFF;
SELECT
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    SPECIALTY,
    STATUS
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG
LIMIT 5;
UPDATE CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG
SET STATUS = 'INACTIVE',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CANCER_CODE = 'CA001';

CREATE OR REPLACE TEMPORARY TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_CANCER_SCD2
AS
SELECT
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,
    COALESCE(UPDATED_AT, CURRENT_TIMESTAMP()) AS UPDATED_AT,

    MD5(
        CONCAT_WS('|',
            COALESCE(CANCER_NAME, ''),
            COALESCE(CANCER_GROUP, ''),
            COALESCE(ICD10_CODE, ''),
            COALESCE(SPECIALTY, ''),
            COALESCE(STATUS, '')
        )
    ) AS HASH_DIFF

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_RAW.RAW_CANCER_CATALOG;
SELECT
    S.CANCER_CODE,
    S.STATUS AS NEW_STATUS,
    D.STATUS AS OLD_STATUS,
    S.HASH_DIFF AS NEW_HASH,
    D.HASH_DIFF AS OLD_HASH
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_CANCER_SCD2 S
JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER D
    ON S.CANCER_CODE = D.CANCER_CODE
   AND D.IS_CURRENT = TRUE
WHERE S.HASH_DIFF <> D.HASH_DIFF;
UPDATE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER D
SET
    EFF_END_TS = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_CANCER_SCD2 S
WHERE D.CANCER_CODE = S.CANCER_CODE
  AND D.IS_CURRENT = TRUE
  AND D.HASH_DIFF <> S.HASH_DIFF;
  INSERT INTO CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
(
    CANCER_CODE,
    CANCER_NAME,
    CANCER_GROUP,
    ICD10_CODE,
    SPECIALTY,
    STATUS,
    HASH_DIFF,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    LOAD_TS
)
SELECT
    S.CANCER_CODE,
    S.CANCER_NAME,
    S.CANCER_GROUP,
    S.ICD10_CODE,
    S.SPECIALTY,
    S.STATUS,
    S.HASH_DIFF,
    CURRENT_TIMESTAMP(),
    '9999-12-31 23:59:59'::TIMESTAMP,
    TRUE,
    CURRENT_TIMESTAMP()
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.TMP_CANCER_SCD2 S
LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER D
    ON S.CANCER_CODE = D.CANCER_CODE
   AND D.IS_CURRENT = TRUE
WHERE D.CANCER_CODE IS NULL;
SELECT
    CANCER_SK,
    CANCER_CODE,
    CANCER_NAME,
    STATUS,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
WHERE CANCER_CODE = 'CA001'
ORDER BY EFF_START_TS;

SELECT
    PATIENT_ID,
    COUNT(*) AS VERSION_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
GROUP BY PATIENT_ID
HAVING COUNT(*) > 1;

SELECT
    PATIENT_ID,
    SEGMENT,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
WHERE PATIENT_ID = 'P0001'
ORDER BY EFF_START_TS;
SELECT
    CANCER_CODE,
    COUNT(*) AS VERSION_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
GROUP BY CANCER_CODE
HAVING COUNT(*) > 1;
SELECT
    CANCER_CODE,
    STATUS,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
WHERE CANCER_CODE = 'CA001'
ORDER BY EFF_START_TS;

SELECT
    PATIENT_ID,
    COUNT(*) AS CURRENT_VERSION_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT
WHERE IS_CURRENT = TRUE
GROUP BY PATIENT_ID
HAVING COUNT(*) > 1;
SELECT
    CANCER_CODE,
    COUNT(*) AS CURRENT_VERSION_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER
WHERE IS_CURRENT = TRUE
GROUP BY CANCER_CODE
HAVING COUNT(*) > 1;
SELECT COUNT(*) AS FACT_COUNT
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER;
SELECT COUNT(*) AS INVALID_FACT_ROWS
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER
WHERE DATE_SK IS NULL
   OR PATIENT_SK IS NULL
   OR PROVIDER_SK IS NULL
   OR CANCER_SK IS NULL;

USE DATABASE CANCER_ONCOLOGY_DB;

USE SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC;

USE WAREHOUSE CANCER_ONCOLOGY_WH;
CREATE OR REPLACE VIEW CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_PATIENT_ENCOUNTERS AS
SELECT
    F.ENCOUNTER_ID,
    F.ENCOUNTER_LINE_ID,

    F.PATIENT_ID,
    P.FIRST_NAME,
    P.LAST_NAME,
    P.GENDER,
    P.DOB,
    P.CITY,
    P.STATE,
    P.COUNTRY,
    P.SEGMENT,
    P.PAYER_ID,

    F.PROVIDER_ID,
    PR.PROVIDER_NAME,
    PR.PROVIDER_TYPE,
    PR.REGION,

    F.CANCER_CODE,
    C.CANCER_NAME,
    C.CANCER_GROUP,
    C.ICD10_CODE,
    C.SPECIALTY,

    F.DISEASE_STAGE,
    F.TREATMENT_TYPE,
    F.REGIMEN_CODE,
    F.BILLED_AMOUNT,
    F.PAYMENT_MODE,
    F.ENCOUNTER_STATUS

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER F

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT P
    ON F.PATIENT_SK = P.PATIENT_SK

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PROVIDER PR
    ON F.PROVIDER_SK = PR.PROVIDER_SK

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER C
    ON F.CANCER_SK = C.CANCER_SK;

CREATE OR REPLACE VIEW CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_PROVIDER_PERFORMANCE AS
SELECT
    F.PROVIDER_ID,
    PR.PROVIDER_NAME,
    PR.PROVIDER_TYPE,
    PR.REGION,

    COUNT(DISTINCT F.ENCOUNTER_ID) AS TOTAL_ENCOUNTERS,
    COUNT(DISTINCT F.PATIENT_ID) AS UNIQUE_PATIENTS,
    SUM(F.BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
    AVG(F.BILLED_AMOUNT) AS AVG_BILLED_AMOUNT

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER F

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PROVIDER PR
    ON F.PROVIDER_SK = PR.PROVIDER_SK

GROUP BY
    F.PROVIDER_ID,
    PR.PROVIDER_NAME,
    PR.PROVIDER_TYPE,
    PR.REGION;

CREATE OR REPLACE VIEW CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_CANCER_ANALYSIS AS
SELECT
    F.CANCER_CODE,
    C.CANCER_NAME,
    C.CANCER_GROUP,
    C.ICD10_CODE,
    C.SPECIALTY,

    COUNT(DISTINCT F.ENCOUNTER_ID) AS TOTAL_ENCOUNTERS,
    COUNT(DISTINCT F.PATIENT_ID) AS UNIQUE_PATIENTS,
    SUM(F.BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
    AVG(F.BILLED_AMOUNT) AS AVG_BILLED_AMOUNT

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER F

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER C
    ON F.CANCER_SK = C.CANCER_SK

GROUP BY
    F.CANCER_CODE,
    C.CANCER_NAME,
    C.CANCER_GROUP,
    C.ICD10_CODE,
    C.SPECIALTY;

CREATE OR REPLACE VIEW CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_EXECUTIVE_SUMMARY AS
SELECT
    COUNT(DISTINCT F.ENCOUNTER_ID) AS TOTAL_ENCOUNTERS,
    COUNT(DISTINCT F.PATIENT_ID) AS TOTAL_PATIENTS,
    COUNT(DISTINCT F.PROVIDER_ID) AS TOTAL_PROVIDERS,
    COUNT(DISTINCT F.CANCER_CODE) AS TOTAL_CANCER_TYPES,
    SUM(F.BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
    AVG(F.BILLED_AMOUNT) AS AVG_BILLED_AMOUNT

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER F;
SHOW VIEWS IN SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC;
SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_EXECUTIVE_SUMMARY;
SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_PATIENT_ENCOUNTERS
LIMIT 10;
SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_PROVIDER_PERFORMANCE
ORDER BY TOTAL_BILLED_AMOUNT DESC;
SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_CANCER_ANALYSIS
ORDER BY TOTAL_ENCOUNTERS DESC;

SELECT
    CURRENT_ACCOUNT(),
    CURRENT_USER(),
    CURRENT_ROLE(),
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

CREATE OR REPLACE VIEW CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_PATIENT_ENCOUNTERS AS
SELECT
    F.ENCOUNTER_ID,
    F.ENCOUNTER_LINE_ID,
    F.DATE_SK,

    F.PATIENT_ID,
    P.FIRST_NAME,
    P.LAST_NAME,
    P.GENDER,
    P.DOB,
    P.CITY,
    P.STATE,
    P.COUNTRY,
    P.SEGMENT,
    P.PAYER_ID,

    F.PROVIDER_ID,
    PR.PROVIDER_NAME,
    PR.PROVIDER_TYPE,
    PR.REGION,

    F.CANCER_CODE,
    C.CANCER_NAME,
    C.CANCER_GROUP,
    C.ICD10_CODE,
    C.SPECIALTY,

    F.DISEASE_STAGE,
    F.TREATMENT_TYPE,
    F.REGIMEN_CODE,
    F.BILLED_AMOUNT,
    F.PAYMENT_MODE,
    F.ENCOUNTER_STATUS

FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER F

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PATIENT P
    ON F.PATIENT_SK = P.PATIENT_SK

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_PROVIDER PR
    ON F.PROVIDER_SK = PR.PROVIDER_SK

LEFT JOIN CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_CANCER C
    ON F.CANCER_SK = C.CANCER_SK;

DESC TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_PATIENT_ENCOUNTERS
LIMIT 5;

DESC TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.FACT_ENCOUNTER;
SHOW TABLES IN SCHEMA CANCER_ONCOLOGY_DB.ONCOLOGY_DW;

SELECT *
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_DATE
LIMIT 5;

DESC TABLE CANCER_ONCOLOGY_DB.ONCOLOGY_DW.DIM_DATE;

SELECT DATE_SK
FROM CANCER_ONCOLOGY_DB.ONCOLOGY_SEMANTIC.VW_PATIENT_ENCOUNTERS
LIMIT 5;









